backend:
  name: github
  repo: felixdb/greenforest-site # Path to your Github repository
  branch: development # Branch to update (master by default)

media_folder: "static/img/uploads" # Folder where user uploaded files should go
public_folder: "img/uploads" # The src attribute for uploaded media will begin with img/uploads

publish_mode: editorial_workflow

collections:
  - name: "pages-en"
    label: "Pages - EN"
    editor:
      preview: false
    files:
      - name: "produits"
        label: "Produits"
        file: "content/singles/products.en.md"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text", required: false}
          - {label: "Titre - H1", name: "titre", widget: "string", required: false}
          - {label: "Retirer des moteurs de recherche", name: "noindex", widget: "boolean", required: false, default: false}
      - name: "cannabis"
        label: "Cannabis"
        file: "content/singles/cannabis.en.md"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text", required: false}
          - {label: "Titre - H1", name: "titre", widget: "string", required: false}
          - {label: "Retirer des moteurs de recherche", name: "noindex", widget: "boolean", required: false, default: false}
      - name: "contact"
        label: "Contact"
        file: "content/singles/contact.en.md"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text", required: false}
          - {label: "Titre - H1", name: "titre", widget: "string", required: false}
          - {label: "Retirer des moteurs de recherche", name: "noindex", widget: "boolean", required: false, default: false}
      - name: "inscription"
        label: "Inscription"
        file: "content/singles/inscription.en.md"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text", required: false}
          - {label: "Titre - H1", name: "titre", widget: "string", required: false}
          - {label: "Retirer des moteurs de recherche", name: "noindex", widget: "boolean", required: false, default: false}
      - name: "membres"
        label: "Membres"
        file: "content/singles/membres.en.md"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text", required: false}
          - {label: "Titre - H1", name: "titre", widget: "string", required: false}
          - {label: "Retirer des moteurs de recherche", name: "noindex", widget: "boolean", required: false, default: false}
      - name: "menu"
        label: "Menu"
        file: "content/singles/menu.en.md"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text", required: false}
          - {label: "Titre - H1", name: "titre", widget: "string", required: false}
          - {label: "Retirer des moteurs de recherche", name: "noindex", widget: "boolean", required: false, default: false}
      - name: "services"
        label: "Services"
        file: "content/singles/services.en.md"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text", required: false}
          - {label: "Titre - H1", name: "titre", widget: "string", required: false}
          - {label: "Retirer des moteurs de recherche", name: "noindex", widget: "boolean", required: false, default: false}
      - name: "accueil"
        label: "Accueil"
        file: "content/_index.en.md"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text", required: false}
          - {label: "Titre - H1", name: "titre", widget: "string", required: false}
          - {label: "Retirer des moteurs de recherche", name: "noindex", widget: "boolean", required: false, default: false}
  - name: "pages-fr"
    label: "Pages - FR"
    editor:
      preview: false
    files:
      - name: "produits"
        label: "Produits"
        file: "content/produits/_index.md"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text", required: false}
          - {label: "Titre - H1", name: "titre", widget: "string", required: false}
          - {label: "Retirer des moteurs de recherche", name: "noindex", widget: "boolean", required: false, default: false}
      - name: "cannabis"
        label: "Cannabis"
        file: "content/singles/cannabis.md"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text", required: false}
          - {label: "Titre - H1", name: "titre", widget: "string", required: false}
          - {label: "Retirer des moteurs de recherche", name: "noindex", widget: "boolean", required: false, default: false}
      - name: "contact"
        label: "Contact"
        file: "content/singles/contact.md"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text", required: false}
          - {label: "Titre - H1", name: "titre", widget: "string", required: false}
          - {label: "Retirer des moteurs de recherche", name: "noindex", widget: "boolean", required: false, default: false}
      - name: "inscription"
        label: "Inscription"
        file: "content/singles/inscription.md"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text", required: false}
          - {label: "Titre - H1", name: "titre", widget: "string", required: false}
          - {label: "Retirer des moteurs de recherche", name: "noindex", widget: "boolean", required: false, default: false}
      - name: "membres"
        label: "Membres"
        file: "content/singles/membres.md"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text", required: false}
          - {label: "Titre - H1", name: "titre", widget: "string", required: false}
          - {label: "Retirer des moteurs de recherche", name: "noindex", widget: "boolean", required: false, default: false}
      - name: "menu"
        label: "Menu"
        file: "content/singles/menu.md"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text", required: false}
          - {label: "Titre - H1", name: "titre", widget: "string", required: false}
          - {label: "Retirer des moteurs de recherche", name: "noindex", widget: "boolean", required: false, default: false}
      - name: "services"
        label: "Services"
        file: "content/singles/services.md"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text", required: false}
          - {label: "Titre - H1", name: "titre", widget: "string", required: false}
          - {label: "Retirer des moteurs de recherche", name: "noindex", widget: "boolean", required: false, default: false}
      - name: "accueil"
        label: "Accueil"
        file: "content/_index.md"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text", required: false}
          - {label: "Titre - H1", name: "titre", widget: "string", required: false}
          - {label: "Retirer des moteurs de recherche", name: "noindex", widget: "boolean", required: false, default: false}
